package com.example.plugweb

object PluginConstants {
    const val PLGN_IS_NETWORK_AVAILABLE = "PLGN_IS_NETWORK_AVAILABLE"
    const val PLGN_DEV_DETAILS = "PLGN_DEV_DETAILS"
    const val PLGN_GET_IP = "PLGN_GET_IP"
    const val PLGN_APP_VERSION = "PLGN_APP_VERSION"
    const val PLGN_OPEN_CAMERA = "PLGN_OPEN_CAMERA"
    const val PLGN_CRNT_LOCALE = "PLGN_CRNT_LOCALE"
    const val PLGN_APP_SIZE_INFO = "PLGN_APP_SIZE_INFO"
    const val PLGN_CHECK_GPS_STATUS = "PLGN_CHECK_GPS_STATUS"
    const val PLGN_CHECK_ACCESSIBILITY_SETTINGS = "PLGN_CHECK_ACCESSIBILITY_SETTINGS"
    const val PLGN_CHECK_BIOMETRIC = "PLGN_CHECK_BIOMETRIC"
}